import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:wealth_os/src/core/constants/app_constants.dart';
import 'package:wealth_os/src/core/environment/app_environment.dart';
import 'package:wealth_os/src/localization/generated/app_localizations.dart';
import 'package:wealth_os/src/navigation/navigation_destination.dart';
import 'package:wealth_os/src/navigation/navigation_shell.dart';
import 'package:wealth_os/src/routing/app_route.dart';
import 'package:wealth_os/src/routing/route_names.dart';
import 'package:wealth_os/src/routing/route_paths.dart';
import 'package:wealth_os/src/routing/route_registry.dart';

/// Builds the application's [GoRouter] from [RouteRegistry].
///
/// An **adapter**. It reads the route table; the route table has never heard of
/// GoRouter. Replacing GoRouter means rewriting this file and nothing else.
///
/// There is no path literal in here, and no hardcoded navigation item. Both the
/// top-level routes and the shell's branches are generated by iterating the
/// registry.
abstract final class RouterConfiguration {
  /// Creates the router. Called once, by `AppRouter`.
  static GoRouter create() {
    // Checked before a single route is built. GoRouter accepts duplicate paths
    // silently, with the second declaration shadowing the first — a bug that
    // surfaces as one screen inexplicably rendering another's content, with no
    // error reported anywhere.
    RouteRegistry.validate();

    return GoRouter(
      initialLocation: RoutePaths.home,
      debugLogDiagnostics: AppEnvironmentConfig.current.isPreProduction,
      routes: <RouteBase>[
        // Routes outside the shell: destinations a user reaches without the
        // navigation bar. Currently just `/`.
        //
        // Derived by exclusion rather than by naming `home` explicitly, so that
        // adding a future full-screen route — onboarding, a sign-in page — needs
        // no change here. It simply arrives with `showInNavigation: false`.
        for (final AppRoute route in RouteRegistry.allRoutes)
          if (!route.showInNavigation)
            GoRoute(
              name: route.nameValue,
              path: route.path,
              builder: (BuildContext context, GoRouterState state) =>
                  _screenFor(route),
            ),

        // Routes inside the shell: everything the navigation bar can reach.
        //
        // `indexedStack` gives each branch its own Navigator and keeps all of
        // them alive. That is what preserves a tab's scroll position and its
        // half-filled form when the user switches away and back — with a plain
        // stack, every switch would rebuild the destination from scratch, and a
        // user mid-way through entering a transaction would lose it by glancing
        // at their dashboard.
        StatefulShellRoute.indexedStack(
          builder: (
            BuildContext context,
            GoRouterState state,
            StatefulNavigationShell navigationShell,
          ) {
            // GoRouter's type is unwrapped here, not inside NavigationShell.
            // The shell takes a widget, an index and a callback — three plain
            // values — so it can be pumped in a test with no router at all.
            return NavigationShell(
              currentIndex: navigationShell.currentIndex,
              onDestinationSelected: (int index) {
                navigationShell.goBranch(
                  index,
                  // Tapping the branch you are already on returns it to its
                  // root, rather than doing nothing. This is the behaviour
                  // users expect from a bottom bar and are surprised by its
                  // absence.
                  initialLocation: index == navigationShell.currentIndex,
                );
              },
              child: navigationShell,
            );
          },
          branches: <StatefulShellBranch>[
            for (final AppRoute route in RouteRegistry.navigationRoutes)
              StatefulShellBranch(
                routes: <RouteBase>[
                  GoRoute(
                    name: route.nameValue,
                    path: route.path,
                    builder: (BuildContext context, GoRouterState state) =>
                        _screenFor(route),
                  ),
                ],
              ),
          ],
        ),
      ],
    );
  }

  /// Maps a route to the widget that renders it.
  ///
  /// When real screens exist this becomes an exhaustive `switch` over
  /// [RouteName], at which point adding a route without giving it a screen will
  /// not compile — which is why [RouteName] was made an enum in Task 009.
  static Widget _screenFor(AppRoute route) {
    if (route.name == RouteName.home) {
      return const AppPlaceholderScreen();
    }
    return ComingSoonPage(route: route);
  }
}

/// The application's root surface, shown at `/`.
///
/// Outside the shell, so it has no navigation bar. This is the widget that lived
/// in `app.dart` before the router arrived; it remains importable from
/// `package:wealth_os/src/app/app.dart`, which re-exports it.
///
/// The title is [AppConstants.appName] rather than a string literal. That
/// constant is the brand name — the one piece of text in the product deliberately
/// *not* translated, which is why `appName` is `"Wealth OS"` in both ARB files.
class AppPlaceholderScreen extends StatelessWidget {
  const AppPlaceholderScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text(AppConstants.appName),
      ),
    );
  }
}

/// The temporary surface shown for every destination in the shell.
///
/// A title and the words "coming soon". No business logic, no state, no
/// navigation affordance of its own — the bar beneath it is the shell's.
///
/// It takes an [AppRoute] rather than a `String`, so it cannot be constructed for
/// a destination that does not exist in the registry.
class ComingSoonPage extends StatelessWidget {
  const ComingSoonPage({required this.route, super.key});

  /// The route this page is standing in for.
  final AppRoute route;

  @override
  Widget build(BuildContext context) {
    final AppLocalizations l10n = AppLocalizations.of(context);

    return Scaffold(
      appBar: AppBar(
        // Shares one derivation with the navigation bar's labels, so a route's
        // title cannot read one way in the app bar and another below it.
        // Not localized — see `temporaryRouteTitle`.
        title: Text(temporaryRouteTitle(route.name)),
      ),
      body: Center(
        child: Text(l10n.comingSoon),
      ),
    );
  }
}
